### ISSUE TITLE
Use HTTPS Connection

### ISSUE THREAD

**Issue by SuriyaaKudoIsc** [LobbyOS/server#2]
Hi @subins2000, :smile: 

can you _set up your server_ with **[SSL](https://en.wikipedia.org/wiki/Secure_Sockets_Layer)**?

> It's important for our visitors to make the connection secure.

Thanks.

_Yours,_
[**Suriyaa Kudo**](https://github.com/SuriyaaKudoIsc) :octocat: 

---
### Documentations

If you need help to set up your server with SSL.

Read docs from HTML5Rocks Community:
- http://www.html5rocks.com/en/tutorials/security/transport-layer-security/

Or read the docs from Google (overview: https://developers.google.com/web/fundamentals/security/?hl=en):
1. https://developers.google.com/web/fundamentals/security/encrypt-in-transit/?hl=en
2. https://developers.google.com/web/fundamentals/security/encrypt-in-transit/why-https?hl=en
3. https://developers.google.com/web/fundamentals/security/encrypt-in-transit/intro-to-security-terminology?hl=en
4. https://developers.google.com/web/fundamentals/security/encrypt-in-transit/generating-keys-and-csr?hl=en
5. https://developers.google.com/web/fundamentals/security/encrypt-in-transit/enable-https-on-your-servers?hl=en
6. https://developers.google.com/web/fundamentals/security/encrypt-in-transit/make-intra-site-urls-relative?hl=en
7. https://developers.google.com/web/fundamentals/security/encrypt-in-transit/redirect-http-to-https?hl=en
8. https://developers.google.com/web/fundamentals/security/encrypt-in-transit/turn-on-strict-transport-security-and-secure-cookies?hl=en
9. https://developers.google.com/web/fundamentals/security/encrypt-in-transit/migration-concerns?hl=en

**Comment by SuriyaaKudoIsc** [comment]
@subins2000 Did you add a HTTPS function for your website?

**Comment by subins2000** [comment]
Yes, Lobby is now using HTTPS connection : https://lobby.subinsb.com

But, connections from Lobby clients to the server is not secured under HTTPS as the Lobby server uses SNI protocol and hence it does not work with old browsers/cURL : https://support.cloudflare.com/hc/en-us/articles/204144518-SSL-FAQ

**Comment by suriyaa** [comment]
@subins2000 I'm going to close this stale issue.
